Repository oconfronto/oconfronto, pull requests merged in 2024-11, with the labels that each got.

#39 chore: update energy recovery rate from 20 to 5
  src/autocron.php
Labels: type:feature

#41 enhancement: lottery level, ticket purchase limit, prize conversion
  src/lottery.php
Labels: type:enhancement

#44 chore: removes unused files in `src/`
  src/avatar.php
  src/backitens.php
  src/beta.php
  src/bugs.php
  src/bugslist.php
  src/captcha_img.php
  src/closed.php
  src/cookies.php
  src/countdown.php
  src/emails.php
  src/erros/400.html
  src/erros/401.html
  src/erros/403.html
  src/erros/404.html
  src/erros/500.html
  src/eventos.php
  src/example.html
  src/fansites.php
  src/hotkeys.html
  src/images.php
  src/img.php
  src/includes/actions/file.php
  src/index.php
  src/menuhide.php
  src/normalizador.php
  src/pagination.class.php
  src/parceria.html
  src/promo.php
  src/recaptchalib.php
  src/register.php
  src/regras2.php
  src/return.php
  src/sendfiles.php
  src/showindex.php
  src/sobre.php
  src/tab.php
  src/tabelaexp.php
  src/tabelahp.php
  src/templates/private_footer.php
  src/test.html
  src/tour.html
  src/treinar.php
  src/tutorial.php
Labels: type:chore

#51 fix: remove fallback to "1" on referrals
  src/register.php
  src/templates/header.php
Labels: type:fix

#52 fix: undefined referral in character selection
  src/characters.php
Labels: type:fix

#49 fix: reduce character name limit from 15 to 12 to prevent layout issues
  static/css/styles.css
Labels: type:fix

#53 fix: transfer potion errors and refactors code
  src/includes/actions/transfer-potions.php
Labels: type:fix, type:refactor
