Repository oconfronto/oconfronto, pull requests merged in 2025-01, with the labels that each got.

#58 chore: Adjusted Item Drop Logic and Database Initialization.
  src/battle/loot_v2.php
  src/init.sql
  src/monster.php
Labels: type:chore

#59 feat: general ui improvements
  src/accountlog.php
  src/battle_log.php
  src/friendslogs.php
  src/home.php
  src/init.sql
  src/inventory_mobile.php
  src/logbat.php
  src/loggold.php
  src/logitem.php
  src/showit.php
  src/showskills.php
  src/taskslogs.php
  src/templates/acc-header.php
  src/templates/header.php
  src/templates/player-friends.php
  src/templates/player-stats.php
  src/templates/player-tasks.php
  src/templates/player-top.php
  src/templates/private_footer.php
  src/templates/private_header.php
  src/userlog.php
  static/css/css.css
  static/css/private/player-top.css
  static/css/private/showit.css
  static/css/style-a.css
  static/css/styles.css
  static/images/private_background.png
  static/images/topo.jpg
Labels: type:feature

#61 Adjustments made to inventory and other small visual details for the …
  src/_inventory.php
  src/battle.php
  src/characters.php
  src/equipit.php
  src/hospt.php
  src/includes/actions/transfer-items.php
  src/includes/actions/transfer-potions.php
  src/includes/items/gift.php
  src/includes/items/goldbar.php
  src/includes/items/magiccrystal.php
  src/inventory_mobile.php
  src/members.php
  src/monster.php
  src/moveit.php
  src/shop.php
  src/showit.php
  src/start.php
  src/templates/private_header.php
  static/css/css.css
  static/js/keys.php
Labels: feature-request

#70 Update inventory_mobile.php
  src/inventory_mobile.php
Labels: bug-report

#73 Fixes: added ?act=attack after raderon.php, preventative "fix", only for completing the mission and Correction of potion image size.
  src/quest1.php
  src/templates/private_header.php
Labels: type:fix

#71 Fixes: Correction of the position where the potion appears on the avatar.
  static/css/css.css
Labels: type:fix

#74 fix: visual updates and critical bugs
  src/battle/triplohit.php
  src/captcha.php
  src/engine.php
  src/hospt.php
  src/includes/actions/transfer-items.php
  src/includes/actions/transfer-potions.php
  src/includes/items/gift.php
  src/includes/items/goldbar.php
  src/includes/items/magiccrystal.php
  src/monster.php
  src/promote.php
  src/quest1.php
  src/quest5.php
  src/quest6.php
  src/quest7.php
  src/quest8.php
  src/quest9.php
  src/templates/player-top.php
  src/templates/private_header.php
  static/css/css.css
  static/images/itens/Amber_Axe.gif
  vhost.d/default_location
Labels: bug-report, type:fix

#75 Adjustment of the XP rate
  src/monster.php
Labels: type:fix
